version: "3.8" 
services: 
  db: 
    image: postgres:15 
    container_name: sweetshop_db 
    restart: always 
    environment: 
      POSTGRES_USER: Sakshi
      POSTGRES_PASSWORD: Sakshi@2004
      POSTGRES_DB: sweetshop 
    ports: 
      - "5432:5432" 
    volumes: 
      - db_data:/var/lib/postgresql/data 
 
volumes: 
  db_data: 
